const content = {
    c000001: {
        slug: `proin-eleifend`,
        type: `paragraph`,
        title: `Paragraph One`,
        short: `Proin eleifend velit eu orci aliquam auctor.`,
        long: `Proin eleifend velit eu orci aliquam auctor. Maecenas fermentum nulla vel nisi sagittis, non faucibus nisl mollis. Maecenas eget volutpat lectus. Quisque at dictum diam. Donec scelerisque, risus quis ullamcorper imperdiet, turpis nibh scelerisque diam, quis luctus erat arcu pulvinar ligula. Mauris rhoncus venenatis nunc, eu laoreet mauris ultricies at. Aliquam semper venenatis purus, et porttitor nibh volutpat eu. Ut nisi orci, lacinia id mattis et, porta eu nisl. Ut iaculis urna in turpis ultrices interdum. Nunc dignissim turpis et pretium ultrices. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Maecenas tincidunt lacus neque, nec mattis tortor aliquam et. Proin ut sollicitudin leo. Vestibulum laoreet, ipsum sit amet fringilla posuere, est eros auctor nisi, ut facilisis ante erat gravida nisl. Morbi sollicitudin, libero sit amet blandit ultricies, mi neque blandit diam, ut suscipit tellus orci in neque. Mauris feugiat odio mi, ut sollicitudin lacus faucibus volutpat.`,
    },
    c000002: {
        slug: `cras-dictum`,
        type: `paragraph`,
        title: `Cras dictum nec metus a lacinia`,
        short: `Donec ac finibus ex.`,
        long: `Donec ac finibus ex. Mauris maximus bibendum turpis quis eleifend. Integer libero nisi, auctor ac justo at, congue vulputate est. Sed id dictum mauris. Morbi tempor lectus eu lacus condimentum pellentesque. Sed vehicula mi sed neque placerat, eu suscipit lacus malesuada. Aenean elementum gravida massa nec sagittis. Cras vel erat molestie, volutpat tortor ut, imperdiet neque. Sed luctus risus eros, eu tincidunt nulla fringilla non. Vestibulum a odio ac elit rutrum condimentum. Maecenas a mi ac velit tristique semper.`,
    }
}
    
const messages = [
    {
        id: 1,
        primary: 'Brunch this week?',
        secondary: "I'll be in the neighbourhood this week. Let's grab a bite to eat",
        person: '/png/avatars/anon.png',
    },
    {
        id: 2,
        primary: 'Birthday Gift',
        secondary: `Do you have a suggestion for a good present for John on his work
      anniversary. I am really confused & would love your thoughts on it.`,
        person: '/png/avatars/avatar-weizang.png',
    },
    {
        id: 3,
        primary: 'Recipe to try',
        secondary: 'I am try out this new BBQ recipe, I think this might be amazing',
        person: '/png/avatars/be-more-steve.png',
    },
    {
        id: 4,
        primary: 'Yes!',
        secondary: 'I have the tickets to the ReactConf for this year.',
        person: '/png/avatars/chix.png',
    },
    {
        id: 5,
        primary: "Doctor's Appointment",
        secondary: 'My appointment for the doctor was rescheduled for next Saturday.',
        person: '/png/avatars/hipster.png',
    },
    {
        id: 6,
        primary: 'Discussion',
        secondary: `Menus that are generated by the bottom app bar (such as a bottom
      navigation drawer or overflow menu) open as bottom sheets at a higher elevation
      than the bar.`,
        person: '/png/avatars/milky.png',
    },
    {
        id: 7,
        primary: 'Summer BBQ',
        secondary: `Who wants to have a cookout this weekend? I just got some furniture
      for my backyard and would love to fire up the grill.`,
        person: '/png/avatars/mumma.png',
    },
];
